[project]
name = "mbio-backend"
version = "2.0.0"
requires-python = ">=3.12"

[tool.setuptools.packages.find]
where = ["."]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
